import assert from "node:assert/strict";
import { describe, it } from "node:test";
import { ZodError } from "zod";
import { adapterConfigSchema } from "../tools/shared/schema/adapter.ts";
import { generatedFileSchema } from "../tools/shared/schema/generated.ts";
import { runtimeStateSchema } from "../tools/shared/schema/runtime.ts";

describe("adapter schema", () => {
  const adapter = {
    schemaVersion: 1,
    platform: "codex",
    surfaceNameRule: "codex-skill",
    outputs: [
      {
        kind: "repo-skill",
        scope: "capability",
        path: ".agents/skills/{{package.id}}-{{capability.id}}/SKILL.md",
        template: "skill.md.hbs",
        textKind: "markdown",
        header: "html-comment",
      },
    ],
  };

  it("accepts a valid adapter config", () => {
    assert.equal(adapterConfigSchema.parse(adapter).platform, "codex");
  });

  it("rejects absolute output paths", () => {
    assert.throws(
      () =>
        adapterConfigSchema.parse({
          ...adapter,
          outputs: [{ ...adapter.outputs[0], path: "C:/tmp/plugin.json" }],
        }),
      ZodError,
    );
  });

  it("rejects parent-directory output paths", () => {
    assert.throws(
      () =>
        adapterConfigSchema.parse({
          ...adapter,
          outputs: [{ ...adapter.outputs[0], path: "../plugin.json" }],
        }),
      ZodError,
    );
  });

  it("requires JSON outputs to use no generated header", () => {
    assert.throws(
      () =>
        adapterConfigSchema.parse({
          ...adapter,
          outputs: [
            {
              ...adapter.outputs[0],
              kind: "plugin-manifest",
              scope: "package",
              path: "plugins/codex/{{package.id}}/.codex-plugin/plugin.json",
              textKind: "json",
              header: "html-comment",
            },
          ],
        }),
      ZodError,
    );
  });
});

describe("generated file schema", () => {
  it("accepts a valid generated file descriptor", () => {
    const file = generatedFileSchema.parse({
      platform: "claude",
      kind: "plugin-skill",
      packageId: "wonder-build",
      capabilityId: "create",
      path: "plugins/claude/wonder-build/skills/create/SKILL.md",
      content: "<!-- GENERATED by WonderSolutions. Source hash: hash. Do not edit. -->\n",
      sourceFiles: [
        "packages/wonder-build/manifest.json",
        "packages/wonder-build/capabilities/create/instruction.md",
      ],
      sourceHash: "hash",
      textKind: "markdown",
      header: "html-comment",
    });

    assert.equal(file.kind, "plugin-skill");
  });
});

describe("runtime state schema", () => {
  it("accepts a valid project-local capability registry", () => {
    const state = runtimeStateSchema.parse({
      schemaVersion: 1,
      plugins: {
        "wonder-build": {
          initialized: true,
          capabilities: {
            create: {
              kind: "workflow",
              surfaces: {
                claude: "/wonder-build:create",
                codex: "$wonder-build-create",
                antigravity: "wonder-build.create",
              },
            },
          },
          platforms: {
            claude: { initialized: true },
            codex: { initialized: false },
            antigravity: { initialized: false },
          },
        },
      },
    });

    assert.equal(state.plugins["wonder-build"]?.platforms.claude.initialized, true);
  });

  it("rejects malformed runtime platform state", () => {
    assert.throws(
      () =>
        runtimeStateSchema.parse({
          schemaVersion: 1,
          plugins: {
            "wonder-build": {
              initialized: true,
              capabilities: {},
              platforms: {
                claude: { initialized: "yes" },
                codex: { initialized: false },
                antigravity: { initialized: false },
              },
            },
          },
        }),
      ZodError,
    );
  });
});
