import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdtemp, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { describe, it } from "node:test";
import { PLATFORMS } from "../tools/shared/platform/names.ts";
import { adapterConfigSchema } from "../tools/shared/schema/adapter.ts";
import { loadSource } from "../tools/generate/src/load-source.ts";
import { computeOutputs } from "../tools/generate/src/compute-output.ts";
import { writeOutputs } from "../tools/generate/src/write-output.ts";

const root = process.cwd();

async function readJson(path: string): Promise<unknown> {
  return JSON.parse(await readFile(join(root, path), "utf8"));
}

describe("adapter source", () => {
  it("defines adapter configs and templates for every target platform", async () => {
    for (const platform of PLATFORMS) {
      const adapter = adapterConfigSchema.parse(await readJson(`adapters/${platform}/adapter.json`));

      assert.equal(adapter.platform, platform);
      for (const output of adapter.outputs) {
        assert.equal(existsSync(join(root, "adapters", platform, "templates", output.template)), true);
      }
    }
  });
});

describe("generator source graph", () => {
  it("loads required package and capability source in canonical order", async () => {
    const graph = await loadSource(root);

    assert.deepEqual(
      graph.packages.map((packageSource) => packageSource.manifest.id),
      ["wonder-build", "wonder-govern", "wonder-reuse", "wonder-extend"],
    );
    assert.deepEqual(
      graph.packages[0]?.capabilities.map((capability) => capability.manifest.id),
      ["init", "create", "modify", "review"],
    );
    assert.deepEqual(Object.keys(graph.adapters), ["claude", "codex", "antigravity"]);
  });
});

describe("generator output computation", () => {
  it("computes deterministic native outputs from the shared source graph", async () => {
    const graph = await loadSource(root);
    const outputs = computeOutputs(graph, ["claude", "codex", "antigravity"]);
    const paths = outputs.map((output) => output.path);

    assert.equal(outputs.length, 74);
    assert.equal(new Set(paths).size, outputs.length);
    assert.ok(paths.includes(".claude-plugin/marketplace.json"));
    assert.ok(paths.includes(".agents/plugins/marketplace.json"));
    assert.ok(paths.includes("plugins/claude/wonder-build/skills/create/SKILL.md"));
    assert.ok(paths.includes("plugins/codex/wonder-build/skills/wonder-build-create/SKILL.md"));
    assert.ok(paths.includes(".agents/skills/wonder-build-create/SKILL.md"));
    assert.ok(paths.includes(".agents/plugins/wonder-build/plugin.json"));
    assert.ok(paths.includes(".agents/plugins/wonder-build/skills/create/SKILL.md"));

    const codexSkill = outputs.find(
      (output) => output.path === "plugins/codex/wonder-build/skills/wonder-build-create/SKILL.md",
    );
    assert.ok(codexSkill);
    assert.match(codexSkill.content, /^<!-- GENERATED by WonderSolutions\. Source hash: [a-f0-9]{64}\. Do not edit\. -->/);
    assert.match(codexSkill.content, /name: wonder-build-create/);
    assert.match(codexSkill.content, /# Create Artifact/);

    const codexManifest = outputs.find(
      (output) => output.path === "plugins/codex/wonder-build/.codex-plugin/plugin.json",
    );
    assert.ok(codexManifest);
    assert.doesNotMatch(codexManifest.content, /GENERATED/);
    assert.equal(JSON.parse(codexManifest.content).skills, "./skills/");
  });
});

describe("generator writes", () => {
  it("writes computed outputs without deleting unrelated native files", async () => {
    const graph = await loadSource(root);
    const outputs = computeOutputs(graph, ["codex"]).slice(0, 3);
    const projectRoot = await mkdtemp(join(tmpdir(), "wonder-generate-"));

    try {
      await writeFile(join(projectRoot, "manual.txt"), "keep\n", "utf8");
      const report = await writeOutputs(projectRoot, outputs, { dryRun: false });

      assert.equal(report.written.length, 3);
      for (const output of outputs) {
        assert.equal(existsSync(join(projectRoot, output.path)), true);
      }
      assert.equal(await readFile(join(projectRoot, "manual.txt"), "utf8"), "keep\n");
    } finally {
      await rm(projectRoot, { recursive: true, force: true });
    }
  });
});
